sparkle/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('register/manager/', views.manager_register, name='manager_register'), 
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(  'password-reset/',
            auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

sparkle/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

sparkle/sparkle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sparkle/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone
from shop.models import Product  

class UserManager(BaseUserManager):
    def create_user(self, email, full_name, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, full_name=full_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, full_name, password=None, **extra_fields):
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, full_name, password, **extra_fields)

class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)
    full_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)  
    likes = models.ManyToManyField(Product, blank=True, related_name='likes')  

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    @property
    def is_staff(self):
        return self.is_admin

    def get_likes_count(self):
        return self.likes.count()

    def has_purchased(self, product):
        return self.orders.filter(items__product=product).exists()

    def is_shop_manager(self):
        return self.is_manager 

sparkle/accounts/forms.py
from django import forms
from .models import User


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'password'}
        )
    )


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}
        )
    )
    full_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'full name'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'password'}
        )
    )


class ManagerLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'password'}
        )
    )


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['full_name', 'email']


class ManagerRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'password'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'repeat password'}))

    class Meta:
        model = User
        fields = ('email', 'full_name')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don’t match.')
        return cd['password2']

sparkle/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from .forms import UserRegistrationForm, UserLoginForm, ManagerLoginForm, EditProfileForm, ManagerRegistrationForm
from accounts.models import User


def manager_register(request):
    if request.method == 'POST':
        form = ManagerRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                data['email'], data['full_name'], data['password']
            )
            user.is_manager = True
            user.save()
            messages.success(request, 'Manager account created successfully.', 'success')
            return redirect('accounts:user_login')
    else:
        form = ManagerRegistrationForm()
    context = {'title': 'Register Manager', 'form': form}
    return render(request, 'manager_register.html', context)


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                data['email'], data['full_name'], data['password']
            )
            return redirect('accounts:user_login')
    else:
        form = UserRegistrationForm()
    context = {'title':'Signup', 'form':form}
    return render(request, 'register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, email=data['email'], password=data['password']
            )
            if user is not None:
                login(request, user)
                return redirect('shop:home_page')
            else:
                messages.error(
                    request, 'username or password is wrong', 'danger'
                )
                return redirect('accounts:user_login')
    else:
        form = UserLoginForm()
    context = {'title':'Login', 'form': form}
    return render(request, 'login.html', context)


def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')


def edit_profile(request):
    form = EditProfileForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        messages.success(request, 'Your profile has been updated', 'success')
        return redirect('accounts:edit_profile')
    else:
        form = EditProfileForm(instance=request.user)
    context = {'title':'Edit Profile', 'form':form}
    return render(request, 'edit_profile.html', context)

sparkle/accounts/templates/edit_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Edit Profile</h3>
            <hr>
            {{ form|crispy  }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock %}

sparkle/accounts/templates/email_template.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

sparkle/accounts/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Login</h3>
            <hr>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
            </div>
            <div class="mt-2 mb-2">
                <small class="">
                    <a class="text-decoration-none text-danger" href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                New Here? <a class="text-decoration-none" href="{% url 'accounts:user_register' %}">Create account</a>
                <br>    
            </small>
        </div>
    </div>
{% endblock %}

sparkle/accounts/templates/manager_register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Register Manager</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %}

sparkle/accounts/templates/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Reset Password</h3>
            <hr>
            <p class="text-danger">Please enter your email that you used in your account.</p>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock %}

sparkle/accounts/templates/password_reset_complete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6 alert alert-success">
        Your Password Has Been Set.
    </div>
    <a href="{% url 'accounts:user_login' %}" class="">Login Here</a>
{% endblock %}

sparkle/accounts/templates/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Reset Password</h3>
            <hr>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock %}

sparkle/accounts/templates/password_reset_done.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6 alert alert-info">
        An Email has been sent with instrunctions to reset your password!
    </div>
{% endblock %}

sparkle/accounts/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Create Account</h3>
            <hr>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary w-100 mt-2" type="submit">Submit</button>
            </div>
        </form>
        <div class="mt-3">
            <small class="text-muted">
                Already have an account? <a href="{% url 'accounts:user_login' %}">Login</a> 
                <br> 
                <a href="{% url 'accounts:manager_register' %}">Register as manager</a>
            </small>
        </div>
    </div>
{% endblock %}